name: feature_collection
description: "A collection of features frequently used in projects."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  core:
    path: core
  navigation:
    path: navigation
  settings_page:
    path: features/settings_page
  domain:
    path: domain

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true